[package]
name = "nodepilot-updater"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nodepilot-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
tracing = { workspace = true }
